# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "speech.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cspeech.proto\x12\x13\x64\x61gloapis.speech.v1"\x83\x01\n\x19StreamingRecognizeRequest\x12\x38\n\x06\x63onfig\x18\x01 \x01(\x0b\x32&.dagloapis.speech.v1.RecognitionConfigH\x00\x12\x17\n\raudio_content\x18\x02 \x01(\x0cH\x00\x42\x13\n\x11streaming_request"C\n\x11RecognitionConfig\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x17\n\x0finterim_results\x18\x02 \x01(\x08"u\n\x1aStreamingRecognizeResponse\x12?\n\x06result\x18\x01 \x01(\x0b\x32/.dagloapis.speech.v1.StreamingRecognitionResult\x12\x16\n\x0etotal_duration\x18\x02 \x01(\x02"Y\n\x1aStreamingRecognitionResult\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x15\n\rlanguage_code\x18\x03 \x01(\t2\x85\x01\n\x06Speech\x12{\n\x12StreamingRecognize\x12..dagloapis.speech.v1.StreamingRecognizeRequest\x1a/.dagloapis.speech.v1.StreamingRecognizeResponse"\x00(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "speech_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STREAMINGRECOGNIZEREQUEST"]._serialized_start = 38
    _globals["_STREAMINGRECOGNIZEREQUEST"]._serialized_end = 169
    _globals["_RECOGNITIONCONFIG"]._serialized_start = 171
    _globals["_RECOGNITIONCONFIG"]._serialized_end = 238
    _globals["_STREAMINGRECOGNIZERESPONSE"]._serialized_start = 240
    _globals["_STREAMINGRECOGNIZERESPONSE"]._serialized_end = 357
    _globals["_STREAMINGRECOGNITIONRESULT"]._serialized_start = 359
    _globals["_STREAMINGRECOGNITIONRESULT"]._serialized_end = 448
    _globals["_SPEECH"]._serialized_start = 451
    _globals["_SPEECH"]._serialized_end = 584
# @@protoc_insertion_point(module_scope)
