# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import speech_pb2 as speech__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in speech_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SpeechStub(object):
    """음성인식 API를 구현하는 서비스"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingRecognize = channel.stream_stream(
            "/dagloapis.speech.v1.Speech/StreamingRecognize",
            request_serializer=speech__pb2.StreamingRecognizeRequest.SerializeToString,
            response_deserializer=speech__pb2.StreamingRecognizeResponse.FromString,
            _registered_method=True,
        )


class SpeechServicer(object):
    """음성인식 API를 구현하는 서비스"""

    def StreamingRecognize(self, request_iterator, context):
        """양방향 스트리밍 방식으로 음성 인식을 수행합니다. 오디오를 전송하는 동시에 결과를 수신합니다."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamingRecognize": grpc.stream_stream_rpc_method_handler(
            servicer.StreamingRecognize,
            request_deserializer=speech__pb2.StreamingRecognizeRequest.FromString,
            response_serializer=speech__pb2.StreamingRecognizeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "dagloapis.speech.v1.Speech", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "dagloapis.speech.v1.Speech", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class Speech(object):
    """음성인식 API를 구현하는 서비스"""

    @staticmethod
    def StreamingRecognize(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/dagloapis.speech.v1.Speech/StreamingRecognize",
            speech__pb2.StreamingRecognizeRequest.SerializeToString,
            speech__pb2.StreamingRecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
